### ISSUE TITLE
Error with poor samples prevents upload

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/auto_qc#15]
Error from run containing samples with 0 reads, as `Per tile sequence quality` metric was not produced by FastQC.

Didn't affect this run as it was a fail anyway, but it wasn't able to skip the run and prevented other runs from being uploaded.

For this run I manually added a failed FastQC Per tile sequence quality line for every sample that didn't have it, but as a long term solution this could automatically be done during upload? 

Error traceback:
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/export/home/webapps/miniconda3/envs/auto_qc/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/export/home/webapps/miniconda3/envs/auto_qc/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/export/home/webapps/miniconda3/envs/auto_qc/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/export/home/webapps/miniconda3/envs/auto_qc/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/state/partition1/home/webapps/auto_qc/qc_database/management/commands/update_database.py", line 1002, in handle
    fastqc_dict = germline_enrichment.get_fastqc_data()
  File "/state/partition1/home/webapps/auto_qc/pipeline_monitoring/pipelines.py", line 212, in get_fastqc_data
    file_fastqc_dict['per_tile_sequence_quality'] = parsed_fastqc_data['Per tile sequence quality']
KeyError: 'Per tile sequence quality'
```

parsed_fastqc_dict output:
```
{
    'UniqueID': '200924_NB551415_0122_AH7WVCAFX2_19M12313', 
    'general_readinfo': '200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq', 
    'SampleID': '19M12313', 
    'RunID': '200924_NB551415_0122_AH7WVCAFX2', 
    'Read_Group': 'R1', 
    'Lane': 'L003', 
    'Basic Statistics': 'PASS', 
    'Per base sequence quality': 'PASS', 
    'Per sequence quality scores': 'PASS', 
    'Per base sequence content': 'FAIL', 
    'Per sequence GC content': 'FAIL', 
    'Per base N content': 'PASS', 
    'Sequence Length Distribution': 'WARN', 
    'Sequence Duplication Levels': 'PASS', 
    'Overrepresented sequences': 'FAIL', 'Adapter Content': 'PASS', 
    'Kmer Content': 'PASS'
}
```

FastQC output - Per tile sequence quality missing:
```
PASS	Basic Statistics	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
PASS	Per base sequence quality	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
PASS	Per sequence quality scores	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
FAIL	Per base sequence content	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
FAIL	Per sequence GC content	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
PASS	Per base N content	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
WARN	Sequence Length Distribution	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
PASS	Sequence Duplication Levels	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
FAIL	Overrepresented sequences	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
PASS	Adapter Content	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
PASS	Kmer Content	200924_NB551415_0122_AH7WVCAFX2_19M12313_L003_R1.fastq
```

**Comment by josephhalstead** [comment]
closed
